// Date: 1/24/2014 9:22:08 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package littlebreadloaf.bleach.render.models.armor;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSoulChain extends ModelBiped
{
  //fields
    ModelRenderer soulchainanchor;
    ModelRenderer soulchainchain;
  
  public ModelSoulChain(float f)
  {
	  super(f);
    textureWidth = 64;
    textureHeight = 32;
    
      soulchainanchor = new ModelRenderer(this, 24, 4);
      soulchainanchor.addBox(1F, 1F, -2.5F, 3, 3, 1);
      soulchainanchor.setRotationPoint(0F, 0F, 0F);
      soulchainanchor.setTextureSize(64, 32);
      soulchainanchor.mirror = true;
      setRotation(soulchainanchor, 0F, 0F, 0.7853982F);
      soulchainchain = new ModelRenderer(this, 0, 0);
      soulchainchain.addBox(-1.5F, 4F, -2F, 3, 7, 0);
      soulchainchain.setRotationPoint(0F, 0F, 0F);
      soulchainchain.setTextureSize(64, 32);
      soulchainchain.mirror = true;
      setRotation(soulchainchain, -0.1396263F, 0F, - 0.7853982F);
      
      this.bipedBody.addChild(soulchainanchor);
      this.soulchainanchor.addChild(soulchainchain);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
